# TypeScript Type Definitions

**Generated from Rust via Specta**  
**Version**: 1.0.0  
**Date**: 2025-12-30

> **Note**: These types will be auto-generated by Specta in production. This file serves as the contract specification.

---

## Core Types

### EditOperation

```typescript
export type EditOperation =
  | FilterOperation
  | AdjustmentOperation
  | TransformOperation
  | CropOperation;

export type OperationType = "filter" | "adjustment" | "transform" | "crop";
```

---

## Operation Types

### FilterOperation

```typescript
export interface FilterOperation {
  id: string;
  type: "filter";
  op: "filter";
  filter_type: FilterType;
  intensity: number;  // Range: 0.0 - 1.0
}

export type FilterType =
  | "grayscale"
  | "sepia"
  | "invert"
  | "blur"
  | "sharpen";
```

**Usage Example**:
```typescript
const grayscaleOp: FilterOperation = {
  id: crypto.randomUUID(),
  type: "filter",
  op: "filter",
  filter_type: "grayscale",
  intensity: 1.0
};
```

---

### AdjustmentOperation

```typescript
export interface AdjustmentOperation {
  id: string;
  type: "adjustment";
  op: "adjustment";
  brightness?: number;   // Range: 0.0 - 2.0, default: 1.0
  contrast?: number;     // Range: 0.0 - 2.0, default: 1.0
  saturation?: number;   // Range: 0.0 - 2.0, default: 1.0
  hue?: number;          // Range: -180 to 180, default: 0
  gamma?: number;        // Range: 0.1 - 3.0, default: 1.0
}
```

**Usage Example**:
```typescript
const brightenOp: AdjustmentOperation = {
  id: crypto.randomUUID(),
  type: "adjustment",
  op: "adjustment",
  brightness: 1.3,
  contrast: 1.1
};
```

---

### TransformOperation

```typescript
export interface TransformOperation {
  id: string;
  type: "transform";
  op: "transform";
  transform_type: TransformType;
}

export type TransformType =
  | { type: "rotate90" }
  | { type: "rotate180" }
  | { type: "rotate270" }
  | { type: "flip_horizontal" }
  | { type: "flip_vertical" };
```

**Usage Example**:
```typescript
const rotateOp: TransformOperation = {
  id: crypto.randomUUID(),
  type: "transform",
  op: "transform",
  transform_type: { type: "rotate90" }
};
```

---

### CropOperation

```typescript
export interface CropOperation {
  id: string;
  type: "crop";
  op: "crop";
  rect: CropRect;
  maintain_aspect_ratio?: number;  // Optional aspect ratio (width/height)
}

export interface CropRect {
  x: number;       // Top-left X coordinate
  y: number;       // Top-left Y coordinate
  width: number;   // Width in pixels (must be > 0)
  height: number;  // Height in pixels (must be > 0)
}
```

**Usage Example**:
```typescript
const cropOp: CropOperation = {
  id: crypto.randomUUID(),
  type: "crop",
  op: "crop",
  rect: {
    x: 100,
    y: 100,
    width: 800,
    height: 600
  },
  maintain_aspect_ratio: 16 / 9
};
```

---

## Command Input Types

### OpenImageInput

```typescript
export interface OpenImageInput {
  path: string;  // Absolute file path
}
```

---

### ApplyOperationInput

```typescript
export interface ApplyOperationInput {
  operation: EditOperation;
  preview_width?: number;  // Optional max preview width
}
```

---

### PreviewInput

```typescript
export interface PreviewInput {
  operations: EditOperation[];
  max_width: number;
  max_height: number;
}
```

---

### ExportInput

```typescript
export interface ExportInput {
  output_path: string;
  operations: EditOperation[];
  format: ExportFormat;
  quality?: number;  // 1-100, only for JPEG/WebP
}

export type ExportFormat = "jpeg" | "png" | "webp";
```

---

## Command Output Types

### OpenImageOutput

```typescript
export interface OpenImageOutput {
  preview_base64: string;  // Data URL format: "data:image/png;base64,..."
  original_width: number;
  original_height: number;
  format: string;          // e.g., "Rgb8", "Rgba8"
}
```

---

### ApplyOperationOutput

```typescript
export interface ApplyOperationOutput {
  preview_base64: string;
  new_width: number;
  new_height: number;
}
```

---

### PreviewOutput

```typescript
export interface PreviewOutput {
  preview_base64: string;
  width: number;
  height: number;
}
```

---

### ExportOutput

```typescript
export interface ExportOutput {
  success: boolean;
  output_path: string;
  file_size: number;  // Size in bytes
}
```

---

### HistoryState

```typescript
export interface HistoryState {
  can_undo: boolean;
  can_redo: boolean;
  history_count: number;
  redo_count: number;
}
```

---

### ClearOutput

```typescript
export interface ClearOutput {
  success: boolean;
}
```

---

## Error Types

### AppError

```typescript
export type AppError =
  | ImageLoadError
  | ImageSaveError
  | UnsupportedFormatError
  | FileAccessDeniedError
  | InvalidOperationError
  | OutOfMemoryError
  | ProcessingError
  | StateError;

export interface ImageLoadError {
  type: "image_load_error";
  message: string;
}

export interface ImageSaveError {
  type: "image_save_error";
  message: string;
}

export interface UnsupportedFormatError {
  type: "unsupported_format";
  message: string;
}

export interface FileAccessDeniedError {
  type: "file_access_denied";
  message: string;
}

export interface InvalidOperationError {
  type: "invalid_operation";
  message: string;
}

export interface OutOfMemoryError {
  type: "out_of_memory";
  required: number;
  available: number;
}

export interface ProcessingError {
  type: "processing_error";
  message: string;
}

export interface StateError {
  type: "state_error";
  message: string;
}
```

---

## Type Guards

```typescript
export function isFilterOperation(op: EditOperation): op is FilterOperation {
  return op.type === "filter";
}

export function isAdjustmentOperation(op: EditOperation): op is AdjustmentOperation {
  return op.type === "adjustment";
}

export function isTransformOperation(op: EditOperation): op is TransformOperation {
  return op.type === "transform";
}

export function isCropOperation(op: EditOperation): op is CropOperation {
  return op.type === "crop";
}

export function isAppError(error: unknown): error is AppError {
  return (
    typeof error === "object" &&
    error !== null &&
    "type" in error &&
    typeof (error as any).type === "string"
  );
}
```

---

## Validation Helpers

```typescript
export function validateAdjustmentParams(op: AdjustmentOperation): string | null {
  if (op.brightness !== undefined && (op.brightness < 0 || op.brightness > 2)) {
    return "Brightness must be between 0.0 and 2.0";
  }
  if (op.contrast !== undefined && (op.contrast < 0 || op.contrast > 2)) {
    return "Contrast must be between 0.0 and 2.0";
  }
  if (op.saturation !== undefined && (op.saturation < 0 || op.saturation > 2)) {
    return "Saturation must be between 0.0 and 2.0";
  }
  if (op.hue !== undefined && (op.hue < -180 || op.hue > 180)) {
    return "Hue must be between -180 and 180";
  }
  if (op.gamma !== undefined && (op.gamma < 0.1 || op.gamma > 3.0)) {
    return "Gamma must be between 0.1 and 3.0";
  }
  return null;
}

export function validateFilterParams(op: FilterOperation): string | null {
  if (op.intensity < 0 || op.intensity > 1) {
    return "Filter intensity must be between 0.0 and 1.0";
  }
  return null;
}

export function validateCropRect(rect: CropRect, imageWidth: number, imageHeight: number): string | null {
  if (rect.width <= 0 || rect.height <= 0) {
    return "Crop dimensions must be positive";
  }
  if (rect.x + rect.width > imageWidth || rect.y + rect.height > imageHeight) {
    return "Crop region exceeds image bounds";
  }
  return null;
}
```

---

## Constants

```typescript
export const VALIDATION_RANGES = {
  adjustment: {
    brightness: { min: 0.0, max: 2.0, default: 1.0 },
    contrast: { min: 0.0, max: 2.0, default: 1.0 },
    saturation: { min: 0.0, max: 2.0, default: 1.0 },
    hue: { min: -180, max: 180, default: 0 },
    gamma: { min: 0.1, max: 3.0, default: 1.0 }
  },
  filter: {
    intensity: { min: 0.0, max: 1.0, default: 1.0 }
  },
  image: {
    maxWidth: 16384,
    maxHeight: 16384,
    maxFileSize: 500 * 1024 * 1024  // 500MB
  },
  export: {
    quality: { min: 1, max: 100, default: 90 }
  }
} as const;

export const SUPPORTED_FORMATS = ["jpeg", "png", "webp"] as const;

export const FILTER_TYPES = ["grayscale", "sepia", "invert", "blur", "sharpen"] as const;

export const TRANSFORM_TYPES = [
  "rotate90",
  "rotate180",
  "rotate270",
  "flip_horizontal",
  "flip_vertical"
] as const;
```

---

## Usage in Frontend

### Example: Tauri Invoke with Type Safety

```typescript
import { invoke } from '@tauri-apps/api/core';
import type { OpenImageInput, OpenImageOutput, AppError } from './types';

async function openImage(filePath: string): Promise<OpenImageOutput> {
  try {
    return await invoke<OpenImageOutput>('open_image', {
      path: filePath
    } satisfies OpenImageInput);
  } catch (error) {
    if (isAppError(error)) {
      throw error;
    }
    throw new Error('Unknown error occurred');
  }
}
```

---

**Generated**: 2025-12-30  
**Auto-generation**: Use `cargo run --bin generate-types` to regenerate from Rust source
